import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.navigation}>Nav</nav>
      <div className={styles.sidebar}>Sidebar</div>
      <div className={styles.leftmenu}>Left Menu</div>
      <main className={styles.content}></main>
      <div className={styles.rightmenu}>Right Menu</div>
    </div>
  )
}
